### ISSUE TITLE
Fine tune model & input data format

### ISSUE THREAD

**Issue by Sixy1204** [kukrishna/pointer-generator-pytorch-allennlp#4]
Hello, I'm a beginner in NLP and interested in your work.
Based on the pre-trained model, I'd like to try fine tuning on my own data. Could you tell me what training data should be like and which python code handles preprocessing? Are there any suggestions on fine tuning your model?
Thanks a lot!

**Comment by kukrishna** [comment]
Hi @Sixy1204 
Sorry for the late response.
The training data format is given in 
https://github.com/kukrishna/pointer-generator-pytorch-allennlp/blob/master/sample_datafile.jsonl
