### ISSUE TITLE
Test output repeat sentence

### ISSUE THREAD

**Issue by Sixy1204** [kukrishna/pointer-generator-pytorch-allennlp#5]
Hello,
When I try to replace sample content with my data (news body and title texts which are corresponding to  “article_lines” and "summary_lines"), the result shows predicted content is most from source body content and repeats itself.
I don't know how to fix it. 
I appreciate your help very much!

**Comment by kukrishna** [comment]
Hi,

Both these observations are common drawbacks of the pointer-generator model
1. Copying lot of content from the source
2. Repeating generated text in the output
They are  detailed in the original paper here
https://arxiv.org/abs/1704.04368

If you use the model checkpoint with coverage, then you can alleviate the repeated generation problem to some extent
