### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Yocodeyo** [kukrishna/pointer-generator-pytorch-allennlp#6]
Thank you for the code implementation for pointer generator!

When I tried to run:
allennlp predict pretrained_model_skeleton.tar.gz --weights-file see_etal_weights_without_coverage.th --include-package pointergen --cuda-device 0 --predictor beamsearch sample_datafile.jsonl
,
it gives me: TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.

May I know how should I solve this issue? Thank you!

**Comment by kukrishna** [comment]
Can you check the version for the "overrides" package?
I think this happened with me at some point and i could fix it by downgrading the overrides package to 3.1.0

`pip install overrides==3.1.0`

**Comment by Yocodeyo** [comment]
It helps! Thanks!

> Can you check the version for the "overrides" package?
> I think this happened with me at some point and i could fix it by downgrading the overrides package to 3.1.0
> 
> `pip install overrides==3.1.0`

However, another issue popped up: ModuleNotFoundError: No module named 'pointergen'.
But I included '--include-package pointergen' and the pointergen folder is in the directory. Do you have any suggestion for this? Thank you!

**Comment by kukrishna** [comment]
Hmm that should not happen. Can you check again that your current directory has the folder "pointergen" in it?

`allennlp predict pretrained_model_skeleton.tar.gz --weights-file see_etal_weights_without_coverage.th --include-package pointergen --cuda-device 0 --predictor beamsearch sample_datafile.jsonl`

It should not give than error.

**Comment by Yocodeyo** [comment]
Sorry my bad! It's solved now!:)

But it gives me: RuntimeError: Error(s) in loading state_dict for Seq2Seq:
	Unexpected key(s) in state_dict: "attention_layer.Wc_layer.weight".

Have you seen similar message before?

**Comment by kukrishna** [comment]
Are you using  `pretrained_model_skeleton_withcoverage.tar.gz` or  ` pretrained_model_skeleton.tar.gz` ?

**Comment by Yocodeyo** [comment]
I'm using pretrained_model_skeleton.tar.gz.

**Comment by kukrishna** [comment]
Use either 
allennlp predict **pretrained_model_skeleton_withcoverage.tar.gz** --weights-file **see_etal_weights_with_coverage.th** --include-package pointergen --cuda-device 0 --predictor beamsearch sample_datafile.jsonl
Or
allennlp predict **pretrained_model_skeleton.tar.gz** --weights-file **see_etal_weights_without_coverage.th** --include-package pointergen --cuda-device 0 --predictor beamsearch sample_datafile.jsonl


First one will give you better results
